#! /bin/sh

sxhkd &
redshift &

xset led 3
feh --bg-fill ~/Pictures/ThisGreatCity.jpg

bspc monitor -d I II III IV V VI 

bspc config top_padding		25
bspc config border_width         4
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config normal_border_color '#e00043'
bspc config focused_border_color '#003da7'
bspc config urgent_border_color '#ff7a99'

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

compton -b &
polybar top &
